---
name: Build and publish image

on:
  workflow_dispatch:
  # push:
    # branches:
      # - 'master'

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Cloning repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push builder image
        run: |
          docker build -t ghcr.io/cakephp/docs-builder .
          docker push ghcr.io/cakephp/docs-builder

      - name: Build and push rungim image
        run: |
          docker build -t ghcr.io/cakephp/docs-builder:runtime -f runtime.Dockerfile .
          docker push ghcr.io/cakephp/docs-builder:runtime
